cd 	CNNCTC_MindSpore/	  && du -sh && pwd && cd ..
cd 	DenseNet/	  && du -sh && pwd && cd ..
cd 	DuConv_mindspore/	  && du -sh && pwd && cd ..
cd 	FCN/	  && du -sh && pwd && cd ..
cd 	FairMOT-mindspore-jupyter/	  && du -sh && pwd && cd ..
cd 	Faster-RCNN/	  && du -sh && pwd && cd ..
cd 	GoogLeNet/	  && du -sh && pwd && cd ..
cd 	HuaweiMindSpore/	  && du -sh && pwd && cd ..
cd 	ICNet/	  && du -sh && pwd && cd ..
cd 	MASS/	  && du -sh && pwd && cd ..
cd 	Mask-RCNN/	  && du -sh && pwd && cd ..
cd 	MindSpore-YOLOv5/	  && du -sh && pwd && cd ..
cd 	OSNet-for-Ascend/	  && du -sh && pwd && cd ..
cd 	SCU-MindSpore-UNnet3D-project/	  && du -sh && pwd && cd ..
cd 	SGD/	  && du -sh && pwd && cd ..
cd 	SSDNet_ms/	  && du -sh && pwd && cd ..
cd 	ShuffleNet/	  && du -sh && pwd && cd ..
cd 	U-Net/	  && du -sh && pwd && cd ..
cd 	VGG16_mindspore/	  && du -sh && pwd && cd ..
cd 	WaveNet/	  && du -sh && pwd && cd ..
cd 	alexnet_mindspore/	  && du -sh && pwd && cd ..
cd 	mind_spore_doc/	  && du -sh && pwd && cd ..
cd 	mindspore-Adam/	  && du -sh && pwd && cd ..
cd 	mindspore-GAN/	  && du -sh && pwd && cd ..
cd 	mindspore_Ghostnet/	  && du -sh && pwd && cd ..
cd 	mindspore_swin_transformer/	  && du -sh && pwd && cd ..
cd 	mingspore-yolox/	  && du -sh && pwd && cd ..
cd 	model-with-mind-spore/	  && du -sh && pwd && cd ..
cd 	pwc_net/	  && du -sh && pwd && cd ..
cd 	squeezenet-mindspore/	  && du -sh && pwd && cd ..
cd 	tiny_bert_ms/	  && du -sh && pwd && cd ..
cd 	wgan/	  && du -sh && pwd && cd ..
